### ISSUE TITLE
Hardcoded path to non-existent libz library in ITKZLIB.cmake

### ISSUE THREAD

**Issue by KrisThielemans** [conda-forge/libitk-feedstock#24] opened 2019-01-19 08:28 UTC
We found this on OSX with current conda. The cmake file refers to
`/Users/travis/miniconda3/conda-bld/libitk_1546796752855/_build_env/lib/libz.dylib`
and therefore all other ITK libraries depend on this file.

Here's an example of a Travis log for our build [https://api.travis-ci.org/v3/job/480922636/log.txt], which seems to say it's using conda-4.5.12 and 4.13.0-hab14342_1001. Not that the log file is somewhat misleading as there `/Users/travis/miniconda3/` does exist (while when building on local machine it doesn't of course).
 
More details are on https://github.com/CCPPETMR/SIRF/pull/295

**Comment by blowekamp** [comment] 2019-01-22 16:48
Is this with just the most recent version? Can you please see if the issue exists with the prior release?

I thought the condo build system is suppose to automatically fix up those dependencies.

**Comment by rijobro** [comment] 2019-01-23 09:10
With an older version of miniconda or itk? 

By the way, the problem is present in miniconda 2 and 3.

**Comment by blowekamp** [comment] 2019-01-23 14:32
An older versions of the libitk package like "osx-64/libitk-4.13.0-0.tar.bz2" or the prior version "osx-64/libitk-4.12.2-0.tar.bz2". Thanks for checking!

**Comment by rijobro** [comment] 2019-01-24 14:58
Sorry, I'm a bit of a novice with anaconda. Our current installation is done like this:
```
wget https://repo.continuum.io/miniconda/Miniconda$PYMVER-latest-MacOSX-x86_64.sh -O miniconda.sh;
bash miniconda.sh -b -p $HOME/miniconda
export PATH="$HOME/miniconda/bin:$PATH"
hash -r
conda config --set always_yes yes --set changeps1 no
conda update -q conda
conda install -c conda-forge libitk
```

Are you saying I should replace the bottom line with `conda install -c conda-forge libitk-4.13.0-0`?

Because that gives the following error:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - libitk-4.13.0-0
```

**Comment by rijobro** [comment] 2019-01-24 15:19
Looks fine with other versions. Just to be clear, installation looks something like this:
```
wget https://repo.continuum.io/miniconda/Miniconda$PYMVER-latest-MacOSX-x86_64.sh -O miniconda.sh;
bash miniconda.sh -b -p $HOME/miniconda
export PATH="$HOME/miniconda/bin:$PATH"
hash -r
conda config --set always_yes yes --set changeps1 no
conda update -q conda
```
problematic method:
```
conda install -c conda-forge libitk
```

working method:
```
wget https://conda.anaconda.org/conda-forge/osx-64/libitk-4.13.0-0.tar.bz2
conda install -p $HOME/ --offline libitk-4.13.0-0.tar.bz2
```

**Comment by blowekamp** [comment] 2019-01-24 15:57
Here is the interesting bit in your build log:
```
[ 86%] Building CXX object src/xSTIR/cSTIR/tests/CMakeFiles/test4.dir/Users/travis/build/CCPPETMR/SIRF-SuperBuild/sources/STIR/src/modelling_buildblock/modelling_registries.cxx.o

make[5]: *** No rule to make target `/Users/travis/miniconda3/conda-bld/libitk_1546796752855/_build_env/lib/libz.dylib', needed by `src/xSTIR/pSTIR/_pystir.so'.  Stop.
```

It indicates that it is not an ITK library that is linked but one of your your libraries which use ITK.

I inspected the distribution libraries and there were no full path links. But in `lib/cmake/ITK-4.13/Modules/ITKZLIB.cmake` There was the following line:

```
ITKZLIB.cmake:set(ITKZLIB_LIBRARIES "/Users/travis/miniconda3/conda-bld/libitk_1546796752855/_build_env/lib/libz.dylib")
```

Which appears to be the root of the problem.

I checked version 4.12.2 and the correct path is there:

```
ITKZLIB.cmake:set(ITKZLIB_LIBRARIES "/Users/blowekamp/miniconda3/lib/libz.dylib")
```

Maybe one of the condo-forge gurus can help with why the build fixed up changed. @bgruening

**Comment by blowekamp** [comment] 2019-01-24 22:53
The original 4.13.0 build 0 does not have this issue. it can be installed with:
```
conda install -c conda-forge libitk=4.13.0=0
```

**Comment by rijobro** [comment] 2019-01-26 11:02
As I said, I installed with:
```
wget https://conda.anaconda.org/conda-forge/osx-64/libitk-4.13.0-0.tar.bz2
conda install -p /usr/rich/Desktop/ITK/ --offline libitk-4.13.0-0.tar.bz2
```
This leads to the following error when buliding against ITK:
```
make[2]: *** No rule to make target `/Users/rich/Desktop/ITK/lib/libexpat.dylib'
```
As far as I can tell, this has to be an ITK error because nothing else is installed to my desktop.

If you think it would remedy the problem (seems unlikely), I can install with:
```
conda install -c conda-forge libitk=4.13.0=0
```

**Comment by blowekamp** [comment] 2019-01-29 13:55
I think it is likely your "offline" command did not properly install the required dependencies of the package. I have not had a change to reproduce, but I'd suggest trying the later command.

**Comment by rijobro** [comment] 2019-01-30 12:00
Hi, I can confirm the following works:
```
conda install -c conda-forge libitk=4.13.0=0
```
Thanks for the help

**Comment by rijobro** [comment] 2019-02-06 16:55
Hi again. The installation works, but libraries are installed with rpaths. This means that when linking against it, I get errors along the lines of:
```
Library not loaded: @rpath/libITKDICOMParser-4.13.1.dylib
Reason: image not found
```

I think there are 3 solutions for this:
1. add `conda/install/location/lib` path to `DYLD_LIBRARY_PATH`
2. run `install_name_tool` on all libraries
3. install ITK with absolute paths

I've tried the first, and it gives the error:
```
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /Users/travis/miniconda/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
```
I'm not prepared to do the second, as it would involve looping over all libraries and looping over all the libraries that they depend on and it would make the Travis script rather unsightly.

So my question is - is it possible to do the third option? Or if not, is there some other solution that I'm not aware of?

**Comment by blowekamp** [comment] 2019-03-26 19:14
@hmaarrfk
@mariusvniekerk 

Any insights as to why the 4.13.0 package container corrected full paths in the installed CMake files, but the more recently built packages contain full paths? The CMake files don't appear to have their paths fixedup any more. Is there a way to specify that these files should be fixed up?

**Comment by hmaarrfk** [comment] 2019-03-26 20:09
Honestly, there were some issues building things a few months back. Maybe try release a new build number and seeing if that helps.

**Comment by isuruf** [comment] 2019-08-09 16:53
In the problematic build, the build env `libz.dylib` was being picked up and the new packages correctly picks up the host env `libz.dylib`. This can be closed

**Closed** 2019-08-20 23:36 UTC
